# syntax=docker/dockerfile:1

FROM scratch AS builder

ADD alpine-minirootfs-3.21.3-x86_64.tar /

ARG VERSION
ENV VERSION=${VERSION}

RUN apk add --no-cache bash busybox-extras

WORKDIR /app

RUN echo "\
<!DOCTYPE html>\n\
<html>\n\
<head><title>Strona Testowa</title></head>\n\
<body>\n\
<h1>Server Info</h1>\n\
<p><strong>IP Address:</strong> \$(hostname -i)</p>\n\
<p><strong>Nazwa Hosta:</strong> \$(hostname)</p>\n\
<p><strong>Wersja Aplikacji:</strong> ${VERSION}</p>\n\
</body>\n\
</html>" > index.html

FROM nginx:alpine AS final

COPY --from=builder /app/index.html /usr/share/nginx/html/index.html

HEALTHCHECK --interval=10s --timeout=5s --start-period=5s --retries=3 \
 CMD wget --spider -q http://localhost || exit 1

CMD ["nginx", "-g", "daemon off;"]

