name: Build and Push Zadanie1 Docker Image

on:
  push:
    paths:
      - 'zadanie1/**'
      - 'Dockerfile'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest, Ubuntu 24.04.2 LTS
    permissions:
      contents: read
      packages: write  # for GHCR
      id-token: write  # for registry logins if using OIDC

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU for multi‑arch emulation
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64, linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug

      - name: Log in to Docker Hub (for cache)
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image with cache
        id: build
        uses: docker/build-push-action@v4
        with:
          context: ./zadanie1
          file: ./zadanie1/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ghcr.io/${{ github.repository_owner }}/zadanie1:${{ github.sha }}
          cache-from: |
            type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/zadanie1-cache:cache
          cache-to: |
            type=registry,mode=max,ref=${{ secrets.DOCKERHUB_USERNAME }}/zadanie1-cache:cache

      - name: Scan for vulnerabilities (Docker Scout)
        uses: docker/scout-action@v0.7.0
        with:
          image: ghcr.io/${{ github.repository_owner }}/zadanie1:${{ github.sha }}
          format: json
          output: scout-report.json
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check scan results
        id: scout-check
        run: |
          high=$(jq '[.vulnerabilities[] | select(.severity=="high" or .severity=="critical")] | length' scout-report.json)
          echo "count=$high" >> $GITHUB_OUTPUT

      - name: Push image if secure
        if: steps.scout-check.outputs.count == '0'
        uses: docker/build-push-action@v4
        with:
          context: ./zadanie1
          file: ./zadanie1/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/zadanie1:latest
            ghcr.io/${{ github.repository_owner }}/zadanie1:${{ github.sha }}
